services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: joaovitor98/restaurante-app
    container_name: app
    tty: true
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    networks:
      - restaurante-app
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    tty: true
    ports:
      - 6380:6379
    networks:
      - restaurante-app
    volumes:
      - /cache/redis:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: joaovitor98/nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - restaurante-app
    tty: true
    restart: unless-stopped
    depends_on:
      - app
networks:
  restaurante-app:
    driver: bridge
